name: Validate
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci --prefer-offline
      - run: npm run lint --if-present
      - run: npm audit --omit dev
        continue-on-error: true
      - run: npm run test --if-present
