name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Release tag and name
jobs:
  release-node:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - shell: bash
        run: npm ci
      - shell: bash
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN}}
        env:
          NODE_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN }}
      - shell: bash
        run: npm publish --access public
      - shell: bash
        run: npm run build:docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Create Release
        run: |
          gh release create ${{ inputs.tag }} --generate-notes
